export const endpoints = {
  login: "/auth/login/",
  refresh: "/auth/refresh/",
  logout: "/auth/logout/",

  courses: "/courses/",
  course: (courseId: string) => `/courses/${courseId}/`,
  landGroups: (courseId: string) => `/courses/${courseId}/land-groups/`,
  officers: (courseId: string) => `/courses/${courseId}/officers/`,
  myOfficerProfile: (courseId: string) => `/courses/${courseId}/officers/me/`,
  directingStaff: (courseId: string) => `/courses/${courseId}/directing-staff/`,
  myDirectingStaffProfile: (courseId: string) => `/courses/${courseId}/directing-staff/me/`,
  activities: (courseId: string) => `/courses/${courseId}/activities/`,
  activity: (courseId: string, activityId: string) => `/courses/${courseId}/activities/${activityId}/`,
  assignments: (courseId: string) => `/courses/${courseId}/assignments/`,
  assignment: (courseId: string, assignmentId: string) => `/courses/${courseId}/assignments/${assignmentId}/`,
  timetable: (courseId: string) => `/courses/${courseId}/timetable/`,
  timetableEntry: (courseId: string, entryId: string) => `/courses/${courseId}/timetable/${entryId}/`,
  assessments: (courseId: string) => `/courses/${courseId}/assessments/`,
  assessment: (courseId: string, assessmentId: string) => `/courses/${courseId}/assessments/${assessmentId}/`,
  submissions: (courseId: string) => `/courses/${courseId}/submissions/`,
  checkPlagiarism: (courseId: string, submissionId: string) =>
    `/courses/${courseId}/submissions/${submissionId}/check-plagiarism/`,
  marks: (courseId: string) => `/courses/${courseId}/marks/`,
  mark: (courseId: string, markId: string) => `/courses/${courseId}/marks/${markId}/`,
  officerProgress: (courseId: string, officerId: string) => `/courses/${courseId}/officers/${officerId}/progress/`,
  progressReport: (courseId: string) => `/courses/${courseId}/progress-report/`,
  assessmentReports: (courseId: string) => `/courses/${courseId}/reports/`,
  announcements: "/announcements/",
  notifications: "/notifications/",
  notification: (notificationId: string) => `/notifications/${notificationId}/`,
  users: "/users/",
  myProfile: "/users/me/",
  updateAvatar: "/users/me/avatar/",
  changePassword: "/users/me/change-password/",
  resetPassword: (userId: string) => `/users/${userId}/reset-password/`,
  deactivateUser: (userId: string) => `/users/${userId}/deactivate/`,
  reactivateUser: (userId: string) => `/users/${userId}/reactivate/`,
  archiveCourse: (courseId: string) => `/courses/${courseId}/archive/`,
} as const;
