# Generated by Django 5.2.17 on 2026-08-24 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instructions', models.TextField(blank=True)),
                ('deadline', models.DateTimeField()),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_schedule', to='activities.activity')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=64)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='activities.activity')),
                ('land_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='courses.landgroup')),
            ],
        ),
    ]
