# Generated by Django 5.2.17 on 2026-08-24 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=512)),
                ('file_type', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF')], max_length=8)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_late', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='scheduling.assessmentschedule')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='personnel.officerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('matches', models.JSONField(blank=True, default=list)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='assessments.submission')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='scheduling.assessmentschedule')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_given', to='personnel.directingstaffprofile')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='personnel.officerprofile')),
            ],
            options={
                'unique_together': {('assessment', 'officer')},
            },
        ),
    ]
