# Generated by Django 5.2.17 on 2026-08-25 15:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('personnel', '0002_alter_directingstaffprofile_user_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='scheduling.assessmentschedule')),
                ('directing_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='personnel.directingstaffprofile')),
            ],
        ),
    ]
