# Generated by Django 5.2.17 on 2026-08-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSearchQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('query_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='plagiarismreport',
            name='matches',
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='external_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plagiarismreport',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='submission',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plagiarismreport',
            name='status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_checked', max_length=16),
        ),
    ]
