# Generated by Django 5.2.17 on 2026-08-24 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='activities.activity')),
                ('directing_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='personnel.directingstaffprofile')),
                ('land_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_assignments', to='courses.landgroup')),
            ],
            options={
                'unique_together': {('activity', 'land_group')},
            },
        ),
    ]
