# Generated by Django 5.2.17 on 2026-08-24 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='directingstaffprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directing_staff_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='directingstaffprofile',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='officerprofile',
            unique_together={('user', 'course')},
        ),
    ]
